version: '3.1'

services:
  broker:
    image: "rabbitmq:3-management"
    hostname: "broker"
    ports:
      - "15672:15672"
      - "5672:5672" # default listener port
    volumes:
      - ./rmq_definitions.json:/opt/rmq_definitions.json:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  producer:
    build: ./producer
    command: npm run build
    environment:
      NODE_ENV: production
      BROKER_HOST: "broker"
      BROKER_PORT: 5672
    volumes:
      - ./producer:/home/dcrmq/producer
      - /home/dcrmq/producer/node_modules
  
  consumer:
    build: ./consumer
    command: npm run build
    environment:
      NODE_ENV: production
      BROKER_HOST: "broker"
      BROKER_PORT: 5672
    volumes:
      - ./consumer:/home/dcrmq/consumer
      - /home/dcrmq/consumer/node_modules
